// Copyright (C) 2023-2024 ConnectorIO Sp. z o.o.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
ifndef::site-gen-antora[]
// pdf output
:author_name: ConnectorIO sp. z o.o.
:author_email: company@connectorio.com
:author: ConnectorIO sp. z o.o.
:email: company@connectorio.com

// custom attributes
:product: ConnectorIO Addons
:openHAB: openHAB
:openHABTrademark: registered trademark of Mr. Kai Kreuzer, it is mentioned in this publication only for information purposes
:publisher: ConnectorIO sp. z o.o.
:copyright-owner: ConnectorIO sp z o.o., Poland.
:copyright: The reproduction, distribution and utilization of this document as well as the communication of its contents to others without express authorization are prohibited.

endif::[]
= Welcome to {page-component-title} documentation

The {page-component-title} is set of open source extensions which aim {openHAB} project.
Extensions described in this documentation helps to monitor various hardware automation systems.

Almost each and every extension described here offers a complete path needed to discover, track  and register reported by integrated hardware.

The {page-component-title} is compatible with {openhab}, an open source project targeted towards home appliances.
It is also compatible with other software distributions which embed {openHAB} project.

== Overview

This document describes installation and configuration procedure of {page-component-title}.
{openHAB} is popular home automation software, however its architecture is extensible through various plugins.
This architecture permits connectivity with many other solutions - including industrial hardware.

The "HAB" part of above name to us is "Hardware Abstraction Bus" (rather than Home Automation Bus), and we ({publisher}) promote this use through provisioning of extensions described in this document.
Vanilla {openHAB} connect to devices such as heating boilers, multimedia systems down to small sensors or smart meters.
It brings also supported for Modbus, various solar inverters, energy meters, some PLC kinds.

== Important notice to reader

include::legal.adoc[]
