= Introduction

{page-component-title} allow plugging typical industrial protocols and hardware into {openHAB}.
{openHAB} is compact project which, once properly installed and configured, can be used as IoT gateway.
With {page-component-title} it will gather connectivity abilities typical for these.

== Concepts

This documentation describes mainly how to configure industrial integrations supplied by {publisher}.
In order to fully understand, "how" various assets are organized in {openHAB}, you need to learn some basic terms.

Main concepts which are used in {openHAB} are:

 * _Bridges_ - usually represents a connection or complex element which can have things.
Be aware, that bridge can be a child of another bridge too.
 * _Things_ - representation of a given functionality, typically representing a piece of hardware or software function.
Main responsibility of this element is to group operations of certain asset in one place.
 * _Channels_ - each thing might have 0 or more channels which are inputs or outputs, generally speaking functions.
A channel represents a single, atomic value or switch which can be controlled or retrieved.
One channel can have 0 or more linked items.
 * _Items_ - items are elements which are created for visualisation and/or persistence purposes.
Since one "thing" can have multiple "channels" the item allows selecting which channels of a device to track.
 * _Links_ - is a relation between item and channel.
For each item-channel pair there is exactly one link.

Keep in mind above definitions because they will be referred in this documentation.
Bindings provided by {publisher} give possibility to create bridges and things which do represent industrial hardware.
First three elements - Bridges, Things, Channels - are defined by shipped integration software.
Last three - Channels, Items and Links - might heavily depend on user configuration.
Especially items and its organization is duty of the end user.

If you still look for additional explanation please read more about https://www.openhab.org/docs/concepts/[concepts used in openHAB].

