// Copyright (C) 2023-2023 ConnectorIO Sp. z o.o.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
=== Disclaimer

This publication is provided as-is, solely for information purposes.

The software is known for its evolution thus changes to its function are expected to happen at any time.
While {publisher} does best effort to keep this documentation inline with {page-component-title}, we can not guarantee it is always up-to-date.
No claims for modification of products that have been applied may be made on basis of materials provisioned by this publication.

=== Trademarks

The {openHAB} is {openHABTrademark}.

Other marks and names used in this publication may be trademarks of their appropriate owners.

{publisher} is not in affiliation nor any other relation with these organizations.
The names of other organizations, solutions and marks are mentioned here solely for information purposes.

The Connectorio® is a trademark owned by and licensed by Code-House, Łukasz Dywicki.

=== Copyright

(C) {docyear} {copyright-owner}

{copyright}