=== BACnet

BACnet is shortcut of "Building Automation and Control Networks".
As name suggests this protocol is very popular in building automation and control applications for HVAC but also other elements in infrastructure.
BACnet is an open standard both in North America (ASHARE) and worldwide (ISO).

The protocol initially defined 23 standard object types, kinds of inputs/outputs and their role in automation systems.
However this number grew up since 1990's.

The ConnectorIO BACnet binding allows to read values from the BACnet network as well as write (command) compatible devices from openHAB.

[NOTE]
====
Currently, this binding uses library licensed under GPL license.
Consider that if you plan to use related code commercially.
====

==== Supported hardware

All devices capable of communication BACnet.

==== Supported things and bridges


|===
|Thing |Type |Name |Description

|ipv4
|bridge
|BACnet/IP bridge
|The BACnet/IP bridge allows to connect devices supporting communication over BACnet/IP.

|ip-device
|bridge
|BACnet/IP device
|Device which is commendable over network connection.

|mstp
|bridge
|BACnet/MSTP Bridge
|The BACnet mstp bridge allows to connect devices communicating over serial interface (RS485).

|mstp-device
|bridge
|BACnet/MSTP device
|Device which is commendable over serial connection.

|===

Following object types are supported:

 * Analog input / output / value
 * Binary input / output / value
 * Multi state input / output / value
 * Pulse converter

For test purposes below object types are available, however they are not officially supported.

 * Schedule (not working)
 * Character String
 * Large analog
 * Octet String
 * Time
 * Integer
 * Positive Integer
 * Date Time Pattern
 * Time Pattern
 * Date Pattern
 * Accumulator

In order to start reading data from BACnet or commanding devices you need to create a valid connection (`mstp` or `ipv4`).
Once done then you can start adding `mstp-device` or `ip-device` instances.
Because BACnet objects have multiple properties they are modelled as separate things.

[WARNING]
====
Currently binding supports only reading/writing of `Present Value` property.
====

[WARNING]
====
Binding does not support Change of Value (COV) notifications yet.
====

==== Textual configuration

Below is example of a text configuration which you can upload to your openhab.
It allows to use a regular version control system to track changes over time.
The same can be done via user interface.

```
Bridge co7io-bacnet:ipv4:local "BACnet Network" [ localNetworkNumber=0, localDeviceId=1010, localBindAddress=10.10.10.10, broadcastAddress="10.10.10.255" ] {

    Bridge ip-device "HVAC unit" [address="10.10.10.20", instance=1, network=0] {
        Thing analog-intput "Exhaust Temperature" [refreshInterval="500"] {
            channels:
                Type writeableNumber: ai1 "Temperature reading" [instance=1]
        }
        Thing analog-intput "Supply Temperature" [refreshInterval="500"] {
            channels:
                Type writeableNumber: ai2 "Temperature reading" [instance=2]
        }

    }
}
```

