==== Changelog

Below list contains summarized list of changes which been introduced over time.
Above documentation describes latest state of integration.
In case if you run older version of integration, please make sure you check earlier documentation.

===== Release 20200501

Released on *May, 2020*.
Compatible with openHAB 2.5.x.

* [Beckhoff] Support for discovery of network enabled devices.
* [Beckhoff] Fixes for doubled connections opened by binding.
* [Beckhoff] Reorganization of connection parameters, introduced `Beckhoff AMS/ADS Network`.
* Fixes causing errors while writing values to PLC.

===== Release 20200102

Released on *January 2nd, 2020*.
Compatible with openHAB 2.5.x.

* [Beckhoff] Fix for error in connection settings causing binding to fail.
* [Beckhoff, Siemens] Introduced support for numeric values.

===== Release 20191231

Released on *December 31th, 2019*.
Compatible with openHAB 2.5.x.

* Initial release with possibility to connect a S7 or ADS device and read binary input/output.

