== Installation and upgrade

Each ConnectorIO binding is one archive.
These archives have a `KAR` extension in their file name.
If you need to use multiple protocols then you will need to repeat below procedure for each of them.

=== Step by step guide

First of all you need to install openHAB.
Please follow official https://www.openhab.org/docs/installation/[openHAB documentation] and find instructions for your hardware platform.

Once your openHAB is up and running you can proceed to installation of bindings.

1. Download selected addons.
2. Locate your openHAB installation.
3. Find addons folder.
 With standard linux/openhabian installations it is `/usr/share/openhab2/addons`.
4. Copy KAR to this folder.
5. Launch browser.
6. Navigate to openHAB server user interface.
7. Pick paperUI from openHAB dashboard.
8. Navigate to Addons > Bindings.
9. Find integration you plan to install by typing protocol or brand name in search box.
10. Click install and wait for operation to complete.

=== Upgrade procedure

Because there is no guarantee which version of binding will start first you need to uninstall earlier version manually.
The procedure for uninstalling is following:

1. Launch browser.
2. Navigate to openHAB server user interface.
3. Pick paperUI from openHAB dashboard.
4. Navigate to Addons > Bindings.
5. Find integration you plan to update.
6. Click uninstall.
7. Go to addons directory and remove selected `KAR` file.
8. Restart openHAB.

Do not worry about things which you created before.
Their definitions and configurations will be kept in openHAB database.
During upgrade, you will just loose ability to read their state.
After successful installation of new version, they should automatically be back to "online" state.

