name: Copybara PR

on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  copybara:
    if: contains(github.event.pull_request.labels.*.name, 'backport') && github.repository == 'connectorio/connectorio-addons'
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_branch: [ 3.1.x, 3.2.x, 3.3.x, 3.4.x ]
      fail-fast: false

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Cache copybara jar
        uses: actions/cache@v3
        with:
          path: bazel-bin/java/com/google/copybara/copybara_deploy.jar
          key: copybara
      - name: Call copybara
        run: >
          java -jar bazel-bin/java/com/google/copybara/copybara_deploy.jar
          migrate .github/copy.bara.sky ${{ matrix.target_branch }}
          ${{ github.event.pull_request.number }}
          --git-committer-email "ci@connectorio.com"
          --git-committer-name "ConnectorIO Bot"
          --git-destination-url="https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          --last-rev ${{ github.event.pull_request.base.sha }}
