name: Maven build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    permissions:
      checks: write
      contents: read
    strategy:
      matrix:
        java: [ 11 ]
        os: [ ubuntu-latest ]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        server-id: co7io-public-snapshots
        server-username: CI_DEPLOY_USERNAME
        server-password: CI_DEPLOY_PASSWORD
    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Calculate branch version
      if: github.event_name == 'pull_request'
      shell: bash
      run: |
        baseVersion=$(mvn org.apache.maven.plugins:maven-help-plugin:3.4.0:evaluate -Dexpression=project.version -q -DforceStdout)
        pullRequestId="pr-${{ github.event.pull_request.number }}"
        mvn versions:set -DnewVersion=${baseVersion//-/"-$pullRequestId-"}
    - name: Build with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: >-
        mvn -B -fae -nsu clean verify
        org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        -Dsonar.projectKey=ConnectorIO_connectorio-addons
        -Dsonar.organization=connectorio
        -Dsonar.host.url=https://sonarcloud.io
    - name: Maven deploy
      if: success()
      env:
        CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
        CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
      run: >-
        mvn -B -nsu package deploy
        -Dmaven.test.skip=true
        -DretryFailedDeploymentCount=3
    - name: Publish Test Report
      if: success() || failure()
      uses: scacap/action-surefire-report@v1
    - name: Upload Test Report
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: "java-test-report-${{ matrix.os }}-java-${{ matrix.java }}"
        path: |
          **/surefire-reports/TEST-*.xml
          **/failsafe-reports/TEST-*.xml
